/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.kute.demo.rpc.thrift.simple.enums;


public enum status implements org.apache.thrift.TEnum {
  PEED(0),
  GOOD(1),
  BAD(2),
  SO(3),
  ASD(10);

  private final int value;

  private status(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static status findByValue(int value) { 
    switch (value) {
      case 0:
        return PEED;
      case 1:
        return GOOD;
      case 2:
        return BAD;
      case 3:
        return SO;
      case 10:
        return ASD;
      default:
        return null;
    }
  }
}
