/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.kute.demo.rpc.thrift.constant;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ConstantConstants {

  public static final double VERSION = 1;

  public static final java.util.Map<java.lang.String,java.lang.String> MAP_CONST = new java.util.HashMap<java.lang.String,java.lang.String>();
  static {
    MAP_CONST.put("hello", "world");
    MAP_CONST.put("goodnight", "moon");
  }

}
